* Create a python program to find `duplicate files` by `content`. User will input path and it will 
scan all directories, sub-directories to find all `duplicates files`.
* `Delete` the found duplicate file

In [31]:
import os
import hashlib
#Function to find duplicate files
def findDuplicate(path):
    hashedFilePath = {}
    for root, dirName, files in os.walk(path):
        for file in files:
            filePath = os.path.join(root, file)
            with open(filePath, 'rb') as f:
                fileHash = hashlib.sha256(f.read()).hexdigest()
            if fileHash in hashedFilePath:
                hashedFilePath[fileHash].append(filePath)
            else:
                hashedFilePath[fileHash] = [filePath]
    return {fileHash:filePath for fileHash, filePath in hashedFilePath.items() if len(filePath) > 1}
# path = input("Enter file path: ")
path = "C:/Users/arysingh/OneDrive - ALLEGIS GROUP/Desktop/Test"
duplicateFiles = findDuplicate(path)
if len(duplicateFiles) == 0:
    print("No Duplicate Files")
else:
    #removing duplicate files
    for fileHash, filePath in duplicateFiles.items():
        print(f"fileHash : {fileHash}")
        for file in filePath[:-1]:
            os.remove(file)


No Duplicate Files


* Generate `random` Password with exact `length = 6`, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters.

In [17]:
import string
import random

uppercase = string.ascii_uppercase
lowercase = string.ascii_lowercase
digits = string.digits
specialChars = string.punctuation.replace("_", "") # Removing underscore
print(specialChars)
password = random.choice(uppercase) 
password += ''.join(random.choices(lowercase, k=2)) 
password += ''.join(random.choices(digits, k=2)) 
password += ''.join(random.choices(specialChars))

password_list = list(password)
random.shuffle(password_list)
password = ''.join(password_list)

print(password)


Qs:3e6


* Create `2D array` and `update` the same 2D array provided that every `prime number position` should be replaced by `cube` of the positioned number.

In [5]:
import numpy as np
def prime(x):
    if x < 2:
        return False
    for i in range(2, x):
        if x % i == 0:
            return False
    return True

def Solution(mat,k= 0):
    for i in range(row):
        for j in range(col):
            if prime(k):
                mat[i][j] = (k) ** 3
            k += 1
    return mat
row = int(input())
col = int(input())
mat = np.arange(0, row*col).reshape((row, col))
Solution(mat)

array([[   0,    1,    8],
       [  27,    4,  125],
       [   6,  343,    8],
       [   9,   10, 1331],
       [  12, 2197,   14],
       [  15,   16, 4913]])

* Python program to get the `sum` of every `cubed value` and its `previous integer`.

In [6]:
import math
def prime(x):
    if x < 2:
        return False
    for i in range(2, x):
        if x % i == 0:
            return False
    return True
#Function to find sum
def findSum(mat, k = 0):
    for i in range(len(mat)):
        for j in range(len(mat[0])):
            if prime(k):
                sum1=0
                if j>0:
                    sum1+= mat[i][j-1]
                else:
                    sum1+=mat[i-1][-1]
                mat[i][j] +=sum1
            k += 1
    return mat

findSum(mat)

array([[   0,    1,    9],
       [  36,    4,  129],
       [   6,  349,    8],
       [   9,   10, 1341],
       [  12, 2209,   14],
       [  15,   16, 4929]])

* Given two arrays, find their `intersection`.
* Input:  arr1[] = [1, 3, 4, 5, 7]
             arr2[] = [2, 3, 5, 6]

In [18]:
#Approach_1
def findIntersection(nums1, nums2, intersectionArr):
    for idx, num in enumerate(set(nums1)):
        if num in nums2:
            intersectionArr.append(num)
    return intersectionArr
nums1 = list(map(int, input().split()))
nums2 = list(map(int, input().split()))
intersectionArr = []
findIntersection(nums1, nums2, intersectionArr)

#Approach_2
def findIntersection(nums1, nums2):
    uniqueNum1 = set(nums1)
    uniqueNum2 = set(nums2)
    intersectionArr = uniqueNum1 & uniqueNum2
    return list(intersectionArr)
nums1 = list(map(int, input().split()))
nums2 = list(map(int, input().split()))
findIntersection(nums1, nums2)

[3, 5]

* Create a `7 x 7`  2D array having only `multiples of 7`. And return the last element of the same.

In [19]:
import numpy as np
row, col = map(int, input().split())
matrxDm = int(input())
matrx = np.arange(matrxDm, matrxDm*(row*col+1), matrxDm).reshape(row, col)
print(matrx)
print(matrx[-1][-1])

[[  7  14  21  28  35  42  49]
 [ 56  63  70  77  84  91  98]
 [105 112 119 126 133 140 147]
 [154 161 168 175 182 189 196]
 [203 210 217 224 231 238 245]
 [252 259 266 273 280 287 294]
 [301 308 315 322 329 336 343]]
343


* `Checker Board` Patten using `Numpy`.
* Example :    
 
    1   0   1   0   1   0   1 <br>
    0   1   0   1   0   1   0 <br>
    1   0   1   0   1   0   1 <br>
    0   1   0   1   0   1   0 <br>
    1   0   1   0   1   0   1 <br>


In [17]:
import numpy as np
def checkerBoard(x, y):
    npArr = np.ones((x, y))
    npArr[1::2, ::2] = 0
    npArr[::2, 1::2] = 0
    return npArr

x, y = map(int, input().split())
checkerBoard(x, y)

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

* Create a given Matrix: <br>
[  <br>
   A,     B,     C,       D <br>
   E,     F,     G,       H <br>
   I,     a,     K,       L <br>
   M,     N,     o,       P <br>
   Q,     R,     S,       T <br>
   U,     0,     W,       O <br>
]
* Replace all the vowels by np.nan
>A, E, I, O U  -- >  np.nan
* Return the count of the missing values

In [10]:
import numpy as np
count = 0
vowels = 'AEIOU'
mat = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'a', 'K', 'L', 'M', 'N', 'o', 'P', 'Q', 'R', 'S', 'T', 'U', '0', 'W', 'O']
for i, ele in enumerate(mat):
    if ele in vowels:
        mat[i] = np.nan
        count += 1
npArr = np.array(mat)
print(npArr.reshape(4,6))
print(count)



[['nan' 'B' 'C' 'D' 'nan' 'F']
 ['G' 'H' 'nan' 'a' 'K' 'L']
 ['M' 'N' 'o' 'P' 'Q' 'R']
 ['S' 'T' 'nan' '0' 'W' 'nan']]
5
